# Ansible
ansible_become: yes
ansible_python_interpreter: 'python3'

# Infra :: Main
system_base_use_resolved: no

# Infra :: Monitoring
zabbix_agent_server_host: 172.29.249.203
zabbix_agent_server_register: no

# Infra :: Keepalived
keepalived_base_instances:
  - name: 'k8s_vip'
    interface: ens160
    auth:
      pass: '1234'
    peers: []
    vips:
      - '172.29.252.30'
    script: check_k8s
# infra_keepalived_scripts:
keepalived_base_scripts:
  - name: check_k8s

# K8S :: Cluster
k8s_control_plane_endpoint: "k8s.dt.ept.lu"

# K8S :: Roles
k8s_roles:
  - k8s_calico
  - k8s_csi-rbd
  - k8s_volsnap
  - k8s_metrics-server
  - k8s_metallb
  - k8s_istio
  - k8s_prometheus

# K8S :: MetalLB
k8s_metallb_pools:
  - name: istio
    protocol: layer2
    auto-assign: false
    addresses: [ "172.29.252.25/32" ]
  - name: harbor
    protocol: layer2
    auto-assign: false
    addresses: [ "172.29.252.26/32" ]
  - name: default
    protocol: layer2
    auto-assign: true
    addresses: [ "172.29.252.27-172.29.252.29" ]


# K8S :: Istio
k8s_istio_version: "1.5.2"
k8s_istio_tls_crt: /usr/local/share/ca-certificates/wildcard.dt.ept.lu.crt
k8s_istio_tls_key: /etc/ssl/private/wildcard.dt.ept.lu.key
k8s_istio_sidecar_namespaces: [ "default" ]
k8s_istio_ingressgw_annotations:
  metallb.universe.tf/address-pool: istio
