- hosts: all
  tasks:
    - include_tasks:
        file: helper_kubeconfig.yml

    - include_tasks:
        file: helper_assert.yml

    - assert:
        that:
          - control_plane_endpoint is defined
          - control_plane_endpoint | length > 0
        fail_msg: "Undefined or empty variable 'control_plane_endpoint'"

    - name: Configure cluster
      include_role:
        name: common/k8s_base
      vars:
        k8s_base_node_type: "{{ facted.kubernetes.role }}"
        k8s_base_kubeconfig: "{{ kubeconfig }}"
        k8s_base_control_plane_endpoint: "{{ control_plane_endpoint }}"
      tags:
        - install
        - configure
        - bootstrap_master
        - bootstrap_worker
        - reset
