- shell: >
    getent passwd {{ ansible_user_id }} | awk -F: '{ print $6 }'
  register: user_home
  tags:
    - always

- name: Find kubeconfig
  set_fact:
    kubeconfig: "{{ user_home.stdout }}/.kube/admin.conf"
  when:
    - kubeconfig is not defined or kubeconfig | length < 1
  tags:
    - always

- debug:
    msg: "{{ item }} ({{ item | length }})"
  loop:
    - user_home
    - kubeconfig
  tags:
    - always
