- name: Find Kubernetes user home directory
  shell: >
    getent passwd "{{ ansible_user_id }}" | cut -d: -f6
  register: _user_homedir

- name: Set kubeconfig path
  set_fact:
    kubeconfig: "{{ _user_homedir.stdout }}/.kube/config"
  when:
    - kubeconfig is not defined or kubeconfig | length < 1
