- shell: >
    getent passwd {{ ansible_user_id }} | awk -F: '{ print $6 }'
  register: user_home
  tags:
    - always

- name: Set kubeconfig from user environment
  set_fact:
    kubeconfig: "{{ user_home.stdout }}/.kube/admin.conf"
  when:
    - kubeconfig is not defined
  tags:
    - always
