- hosts: all
  tasks:
    - include_tasks:
        file: helper_kubeconfig.yml

    - include_tasks:
        file: helper_assert.yml

    - name: Configure service mesh
      include_role:
        name: common/k8s_mesh
      vars:
        k8s_mesh_kubeconfig: "{{ kubeconfig }}"
      run_once: yes
      when:
        - facted.kubernetes.role == "master"
      tags:
        - apply
        - delete
