- hosts: all
  tasks:
    - include_tasks:
        file: helper_kubeconfig.yml

    - include_tasks:
        file: helper_assert.yml

    - name: Configure hosts
      include_role:
        name: common/docker_base
      tags:
        - install
        - configure
        - reset
