- src: git+https://git.dt.ept.lu/iac/ansible/roles/common/
  version: master
  name: common
  scm: git

- src: git+https://git.dt.ept.lu/iac/ansible/roles/k8s_calico
  version: master
  scm: git

- src: git+https://git.dt.ept.lu/iac/ansible/roles/k8s_istio
  version: master
  scm: git


- src: git+https://git.dt.ept.lu/iac/ansible/roles/k8s_gitlab
  version: master
  scm: git