# K8S - GitLab
# Add a Kubernetes cluster to a GitLab group or project.

- hosts:
    - masters

  tasks:

    - include_tasks:
        file: helpers/inventory.yml
        apply: { tags: [ always ] }
      tags:
        - always
    
    - include_role:
        name: k8s_gitlab
      tags:
        - always
