# NOT YET FUNCTIONAL
# DO NOT USE

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ service_name }}
  labels:
    app: {{ service_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ service_name }}
  template:
    metadata:
      labels:
        app: {{ service_name }}
    spec:
      containers:
        - name: {{ service_name }}
          image: venilnoronha/tcp-echo-server:latest
          ports:
            - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: {{ service_name }}
  labels:
    app: {{ service_name }}
    service: {{ service_name }}
spec:
  ports:
    - port: {{ service_port }}
      targetPort: 9000
      name: http
  selector:
    app: {{ service_name }}

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ service_name }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ gateway_name }}
  http:
    - match:
        - port: 1234
      route:
        - destination:
            host: {{ service_name }}
            port:
              number: {{ service_port }}
