# code: language=Ansible insertSpaces=true tabSize=2


- name: Upgrade kubeadm
  shell: >
    apt-get install -y --allow-change-held-packages
    kubeadm={{ kube_version_apt }}


- name: Manual action required to continue
  debug:
    msg:
      - Finished 'kubeadm' upgrade on primary master node {{ inventory_hostname }}.
      - Please run 'kubeadm upgrade plan' then 'kubeadm upgrade apply v{{ kube_version }}' on the primary master node {{ inventory_hostname }}.
      - Once the commands ran, please relaunch the playbook with tags 'masters' to finish the master nodes upgrade.
