# code: language=Ansible insertSpaces=true tabSize=2

# Ansible
# 24/11/2020 - Cluster update - Removed this block
# ansible_user: ansctl
# ansible_become: yes
# ansible_python_interpreter: 'python3'

# Ansible
# 24/11/2020 - Cluster update - Added this block
ansible_become: true
ansible_python_interpreter: 'python3'

# System :: DNS
# 24/11/2020 - Cluster update - Removed this block
# system_dns_resolver: resolv.conf

# Infra :: Main
system_base_use_resolved: false

# Zabbix :: Agent
zabbix_agent_server_host: 172.29.249.203
zabbix_agent_server_register: false

# Infra :: Keepalived
# 24/11/2020 - Cluster update - Removed this block
# infra_keepalived_instances:
#   - name: 'k8s_vip'
#     auth:
#       pass: '1234'
#     peers: []
#     vips:
#       - '172.29.252.54'
#     script: check_k8s
# infra_keepalived_scripts:
#   - name: check_k8s

# K8S :: Cluster
k8s_base_version: "1.20.2-00"
k8s_control_plane_endpoint: "awx-master-01.dt.ept.lu"

# K8S :: Ceph
ceph_client_k8s_pool: awx_prod

# # K8S :: Roles
# k8s_roles:
#   - k8s_calico
#   - k8s_istio
#   - k8s_prometheus

# K8S :: Roles
# 24/11/2020 - Cluster update - Added this block
k8s_roles:
  - k8s_calico
  - k8s_csi-rbd
  - k8s_metrics-server
  - k8s_metallb
  # - k8s_istio
  # - k8s_prometheus
  # - k8s_argocd

# K8S :: MetalLB
# 24/11/2020 - Cluster update - Added this block
# 26/07/2021 - Renamed pool 'istio' to default
k8s_metallb_pools:
  # - name: istio
  #   protocol: layer2
  #   auto-assign: false
  #   addresses: ["172.29.252.54/32"]
  - name: default
    protocol: layer2
    auto-assign: false
    addresses: ["172.29.252.54/32"]

# K8S :: Roles :: Istio
# 24/11/2020 - Cluster update - Removed this block
# k8s_istio_version: "1.5.2"
# k8s_istio_tls_crt: /usr/local/share/ca-certificates/wildcard.dt.ept.lu.crt
# k8s_istio_tls_key: /etc/ssl/private/wildcard.dt.ept.lu.key
# k8s_istio_sidecar_namespaces: [ default, awx, nifi ]
# k8s_istio_ingressgw_custom: "ingressgw-daemonset"
# k8s_istio_ingressgw_ports:
#   # HTTP
#   - containerPort: 80
#     hostPort: 80
#     protocol: TCP
#     name: http2
#   # HTTPS
#   - containerPort: 443
#     hostPort: 443
#     protocol: TCP
#     name: https
# k8s_istio_custom_manifests: [ "gateway", "hellogo" ]
# k8s_istio_custom_gateway_apiVersion: "v1alpha3"

# K8S :: Roles :: Istio
# 24/11/2020 - Cluster update - Added this block
# 26/07/2021 - Istio => Traefik - Removed this block
# k8s_istio_version: "1.5.2"
# k8s_istio_tls_crt: /usr/local/share/ca-certificates/wildcard.dt.ept.lu.crt
# k8s_istio_tls_key: /etc/ssl/private/wildcard.dt.ept.lu.key
# k8s_istio_sidecar_namespaces: [default, awx, nifi, argocd]
# k8s_istio_ingressgw_annotations:
#   metallb.universe.tf/address-pool: istio

# K8S :: Prometheus
# 24/11/2020 - Cluster update - Removed this block
# k8s_prometheus_custom_manifests: [ "istio-vs" ]
# k8s_prometheus_custom_istio_apiVersion: "v1alpha3"

# K8S :: ArgoCD
# 24/11/2020 - Cluster update - Added this block
# 26/07/2021 - Refresh - Removed this block
# k8s_argocd_custom_manifests: [ "istio-virtualservice" ]
# k8s_argocd_istio_vs_hosts: [ "argocd.dt.ept.lu" ]
