---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ service_name }}
  labels:
    app: {{ service_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ service_name }}
  template:
    metadata:
      labels:
        app: {{ service_name }}
    spec:
      containers:
        - name: {{ service_name }}
          image: gcr.io/google-samples/node-hello:1.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: {{ service_name }}
  labels:
    app: {{ service_name }}
    service: {{ service_name }}
spec:
  ports:
    - port: {{ service_port }}
      targetPort: 8080
      name: http
  selector:
    app: {{ service_name }}

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ service_name }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ gateway_name }}
  http:
    - match:
        - uri:
            prefix: "/{{ service_name }}"
      route:
        - destination:
            host: {{ service_name }}
            port:
              number: {{ service_port }}
