---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ gateway_name }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: {{ gateway_port | default(1234) }}
      name: tcp
      protocol: TCP
    hosts:
      - "*"
