# Variables defined here:
# - props.nodePort (integer): Service node port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 2
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: hello-world
          image: gcr.io/google-samples/node-hello:1.0
          ports:
            - containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    run: load-balancer-example
  type: NodePort
  ports:
    - port: 8080
      nodePort: "{{ props.nodePort }}"
      protocol: TCP
