# code: language=Ansible insertSpaces=true tabSize=2
#
# Kubernetes - Ceph
# Setup a Ceph StorageClass on a Kubernetes cluster.

- hosts:
    - ceph_mons
    - k8s_masters

  tasks:

    - name: Gather Ceph cluster facts
      include_role:
        name: ceph_client_k8s
        tasks_from: ceph_facts
        apply: { tags: [ apply ] }
      when:
        - inventory_hostname in groups['ceph_mons']
      tags: [never, apply]


    - name: Set Ceph cluster facts
      set_fact:
        ceph_client_k8s_key: "{{ hostvars[item].ceph_client_k8s_key | default('') }}"
        ceph_client_k8s_cid: "{{ hostvars[item].ceph_client_k8s_cid | default('') }}"
      when:
        - inventory_hostname not in groups['ceph_mons']
        - item in groups['ceph_mons']
      with_items: "{{ ansible_play_hosts }}"
      tags: [never, apply]


    - name: Set Ceph servers from host group
      set_fact:
        ceph_client_k8s_mons: "{{ groups['ceph_mons'] }}"
      when:
        - inventory_hostname in groups['k8s_masters']
        - ceph_client_k8s_mons | default([]) | length < 1
      tags: [never, apply]

# ---

- hosts:
    - k8s_masters

  tasks:

    - include_tasks:
        file: helpers/inventory.yml
        apply: { tags: [ always ] }
      tags: [always]


    # Set the list of Ceph monitors from a commas-separated string.
    # Useful when called from AWX or CLI.
    - set_fact:
        ceph_client_k8s_mons: "{{ ceph_mons.split(',') | list }}"
      when:
        - ceph_mons is defined
        - ceph_mons is string
      tags: [never, apply]


    - include_role:
        role: ceph_client_k8s
      tags: [never, apply, delete]
