# code: language=Ansible insertSpaces=true tabSize=2


# K8S - Restart
# Restart a Kubernetes cluster.

- hosts:
    - k8s_masters
    - k8s_workers

  serial: 1

  tasks:

    - include_tasks:
        file: helpers/inventory.yml
        apply: { tags: [ always ] }
      tags: [always]


    - name: Drain worker node
      shell: >
        kubectl drain {{ inventory_hostname }} --ignore-daemonsets
        || kubectl drain {{ inventory_hostname.split('.')[0] }} --ignore-daemonsets
      delegate_to: "{{ k8s_primary_master_name }}"
      when:
        - k8s_node_type == "worker"
        - k8s_node_type not in ansible_skip_tags


    - name: Stop kubelet
      service:
        name: kubelet
        state: stopped
        enabled: yes
      when:
        - k8s_node_type not in ansible_skip_tags


    - name: Restart Docker
      service:
        name: docker
        state: restarted
        enabled: yes
      when:
        - k8s_node_type not in ansible_skip_tags
      

    - name: Start kubelet
      service:
        name: kubelet
        state: restarted
        enabled: yes
      when:
        - k8s_node_type not in ansible_skip_tags


    - name: Uncordon worker node
      shell: >
        kubectl uncordon {{ inventory_hostname }}
        || kubectl uncordon {{ inventory_hostname.split('.')[0] }}
      delegate_to: "{{ k8s_primary_master_name }}"
      when:
        - k8s_node_type == "worker"
        - k8s_node_type not in ansible_skip_tags
